rails/config/routes.rb
Rails.application.routes.draw do
  resources :steps
  resources :steps
  resources :steps
  resources :groups
  resources :scenarios
  resources :scenarios
  resources :scenarios

  get 'scenarios/:scenario_id/groups/:group_id', :to => 'steps#index'
  get 'groups/:id', :to => 'groups#show'
  resources :scenarios do
    resources :groups, except: :show do
      resources :steps
    end
  end
  resources :groups
  resources :steps

  root 'scenarios#index'

end

rails/app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :scenario
  has_many :steps
end

rails/app/models/scenario.rb
class Scenario < ActiveRecord::Base
  has_many :groups
end

rails/app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :group
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    group = Group.where(string_id: params[:id]).first
    data = group.attributes
    data[:steps] = group.steps.to_a
    respond_to do |format|
        format.html
        format.json { render json: data }
      end
    end
    

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.string_id = SecureRandom.hex
    scenario = Scenario.find(@group.scenario_id)
    respond_to do |format|
      if @group.save
        format.html { redirect_to scenario, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy!
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.where(string_id: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:site_url, :scenario_id)
    end
end

rails/app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :set_scenario, only: [:show, :edit, :update, :destroy]

  # GET /scenarios
  # GET /scenarios.json
  def index
    @scenarios = Scenario.all
  end

  # GET /scenarios/1
  # GET /scenarios/1.json
  def show
    @groups = Scenario.find(params[:id]).groups
    @steps = {}
    @groups.each do |group|
      @steps[group.id] = group.steps.to_a
    end
  end

  # GET /scenarios/new
  def new
    @scenario = Scenario.new
  end

  # GET /scenarios/1/edit
  def edit
  end

  # POST /scenarios
  # POST /scenarios.json
  def create
    @scenario = Scenario.new(scenario_params)

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to @scenario, notice: 'Scenario was successfully created.' }
        format.json { render :show, status: :created, location: @scenario }
      else
        format.html { render :new }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenarios/1
  # PATCH/PUT /scenarios/1.json
  def update
    respond_to do |format|
      if @scenario.update(scenario_params)
        format.html { redirect_to @scenario, notice: 'Scenario was successfully updated.' }
        format.json { render :show, status: :ok, location: @scenario }
      else
        format.html { render :edit }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenarios/1
  # DELETE /scenarios/1.json
  def destroy
    @scenario.destroy!
    respond_to do |format|
      format.html { redirect_to scenarios_url, notice: 'Scenario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_scenario
    @scenario = Scenario.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def scenario_params
    params.require(:scenario).permit(:name)
  end
end

rails/app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]

  # GET /steps
  # GET /steps.json
  def index
    if params[:scenario_id] || params[:group_id]
      group = Group.where(scenario_id: params[:scenario_id], site_url: URI.unescape(params[:group_id])).first
      render json: nil unless group
      data = group.attributes
      data[:steps] = group.steps.to_a
      render json: data
    else
      @steps = Step.all
    end
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
  end

  # GET /steps/new
  def new
    @step = Step.new
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = Step.new(step_params)
    group = Group.find(@step.group_id)
    scenario = Scenario.find(group.scenario_id)

    respond_to do |format|
      if @step.save
        format.html { redirect_to scenario, notice: 'Step was successfully created.' }
        format.json { render :show, status: :created, location: @step }
      else
        format.html { render :new }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to @step, notice: 'Step was successfully updated.' }
        format.json { render :show, status: :ok, location: @step }
      else
        format.html { render :edit }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step.destroy
    respond_to do |format|
      format.html { redirect_to steps_url, notice: 'Step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:message, :error_message, :options, :step_type, :group_id)
    end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/groups_controller_helper.rb
module GroupsControllerHelper
end

rails/app/helpers/groups_helper.rb
module GroupsHelper
end

rails/app/helpers/scenarios_controller_helper.rb
module ScenariosControllerHelper
end

rails/app/helpers/scenarios_helper.rb
module ScenariosHelper
  def step_type(index)
    case index.to_i
    when 1
      "Informacja"
    when 2
      "Pytanie"
    when 3
      "Interakcja"
    else
      "ERROR"
    end
  end
end

rails/app/helpers/steps_controller_helper.rb
module StepsControllerHelper
end

rails/app/helpers/steps_helper.rb
module StepsHelper
end

rails/app/views/groups/_form.html.erb
<%= form_for @group, :html => { :class => "form-horizontal group" } do |f| %>

  <% if @group.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :site_url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :site_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:site_url) %>
  </div>
  <div class="form-group">
    <%= f.label :scenario_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :scenario_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:scenario_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                groups_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

rails/app/views/groups/edit.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

rails/app/views/groups/index.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:site_url) %></th>
      <th><%= model_class.human_attribute_name(:scenario_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.id, group_path(group) %></td>
        <td><%= group.site_url %></td>
        <td><%= group.scenario_id %></td>
        <td><%=l group.created_at %></td>
        <td>
          <%= link_to "Copy Link",
            "#", :class => 'btn btn-default btn-xs', 'data-clipboard-text'=>"#{group.string_id}" %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_group_path(group), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      group_path(group),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_group_path,
            :class => 'btn btn-primary' %>

rails/app/views/groups/new.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

rails/app/views/groups/show.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:site_url) %>:</strong></dt>
  <dd><%= @group.site_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:scenario_id) %>:</strong></dt>
  <dd><%= @group.scenario_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:string_id) %>:</strong></dt>
  <dd><%= @group.string_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              groups_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_group_path(@group), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              group_path(@group),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Guide-App Szlachetnej Paczki</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <a href="#Top"></a>
</head>
<body style="width:80%;margin: 0 auto">
  <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Guide-App Szlachetnej Paczki", "/", :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Scenarios", scenarios_path %></li>
          <li><%= link_to "Groups", groups_path %></li>
          <li><%= link_to "Steps", steps_path  %></li>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar -->

  <% if current_page?(root_path) %>
    <% if content_for?(:jumbotron) %>
      <div class="jumbotron">
        <div class="container">
          <%= yield :jumbotron %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="container">
  <% end %>
  <%= yield %>
  <footer>
    <hr>
      <p class="pull-right">
        <%= link_to '<span class="glyphicon-class glyphicon glyphicon-chevron-up"></span> Back to top'.html_safe, '#Top' %>
      </p>
      <p>
        &copy; <%= Time.now.year %> Guide-App Szlachetnej Paczki
        &bull;
        <%= link_to "Privacy", root_path %></li>
        &bull;
        <%= link_to "Terms", root_path %></li>
      </p>
    </footer>
  </div> <!-- /container -->
  <script id="info-window" type="text/x-handlebars-template">
      <div class="guide-app">
          <div class="guide-app-box">
            <div class="guide-app-subcontrol guide-app-fold">
              <i class="fa fa-circle"></i>
            </div>
            <div class="guide-app-subcontrol guide-app-prev">
              {{{prev-button}}}
            </div>
            <div class="guide-app-text" style="width: 80%;">
              {{text}}
            </div>
            <div class="guide-app-decision">
              {{{info-window-continue-button}}}
            </div>
            <div class="guide-app-subcontrol guide-app-next">
              {{{next-button}}}
            </div>
            <div class="guide-app-pagination">
              {{curr_step}} z {{tot_steps}}
            </div>
          </div>
        </div>
    </script>
    <script id="waiting-window" type="text/x-handlebars-template">
        <div class="guide-app">
          <div class="guide-app-box">
            <div class="guide-app-subcontrol guide-app-fold">
              <i class="fa fa-circle"></i>
            </div>
            <div class="guide-app-subcontrol guide-app-prev">
              {{{prev-button}}}
            </div>
            <div class="guide-app-text">
              {{text}}
            </div>
            <div class="guide-app-decision">
              {{{waiting-window-waiting-icon}}}
            </div>
            <div class="guide-app-subcontrol guide-app-next">
              {{{next-button}}}
            </div>
            <div class="guide-app-pagination">
              {{curr_step}} z {{tot_steps}}
            </div>
          </div>
        </div>
    </script>
    <script id="yesorno-window" type="text/x-handlebars-template">
        <div class="guide-app">
          <div class="guide-app-box">
            <div class="guide-app-subcontrol guide-app-fold">
              <i class="fa fa-circle"></i>
            </div>
            <div class="guide-app-subcontrol guide-app-prev">
              {{{prev-button}}}
            </div>
            <div class="guide-app-text">
              {{text}}
            </div>
            <div class="guide-app-decision">
              {{{yesorno-window-yes-button}}}
              {{{yesorno-window-no-button}}}
            </div>
            <div class="guide-app-subcontrol guide-app-next">
              {{{next-button}}}
            </div>
            <div class="guide-app-pagination">
              {{curr_step}} z {{tot_steps}}
            </div>
          </div>
        </div>
    </script>
    <script id="error-window" type="text/x-handlebars-template">
        <div class="guide-app guide-app-error">
          <div class="guide-app-box">
            <div class="guide-app-subcontrol guide-app-fold">
              <i class="fa fa-circle"></i>
            </div>
            <div class="guide-app-subcontrol guide-app-prev">
              {{{prev-button}}}
            </div>
            <div class="guide-app-text" style="width: 75%">
              {{text}}
            </div>
            <div class="guide-app-decision">
              {{{error-window-next-button}}}
            </div>
            <div class="guide-app-subcontrol guide-app-next">
              {{{next-button}}}
            </div>
          </div>
        </div>
    </script>
    <script id="rating-window" type="text/x-handlebars-template">
        <div class="guide-app">
          <div class="guide-app-box">
            <div class="guide-app-subcontrol guide-app-fold">
              <i class="fa fa-circle"></i>
            </div>
            <div class="guide-app-subcontrol guide-app-prev">
              <i class="fa fa-angle-left"></i>
            </div>
            <div class="guide-app-text">
              {{text}}
            </div>
            <div class="guide-app-rating">
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star-half-o"></i>
              <i class="fa fa-star-o"></i>
            </div>
            <div class="guide-app-subcontrol guide-app-next">
              <i class="fa fa-angle-right"></i>
            </div>
            <div class="guide-app-pagination">
              {{curr_step}} z {{tot_steps}}
            </div>
          </div>
        </div>
    </script>
</body>
</html>

rails/app/views/scenarios/_form.html.erb
<%= form_for @scenario, :html => { :class => "form-horizontal scenario" } do |f| %>

  <% if @scenario.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@scenario.errors.count, "error") %> prohibited this scenario from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @scenario.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                scenarios_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

rails/app/views/scenarios/edit.html.erb
<%- model_class = Scenario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

rails/app/views/scenarios/index.html.erb
<%- model_class = Scenario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @scenarios.each do |scenario| %>
      <tr>
        <td><%= link_to scenario.id, scenario_path(scenario) %></td>
        <td><%= scenario.name %></td>
        <td><%=l scenario.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_scenario_path(scenario), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      scenario_path(scenario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>




<%= link_to t('.new', :default => t("helpers.links.new")),
            new_scenario_path,
            :class => 'btn btn-primary custom-new-scenario' %>

<form class="form-horizontal scenario custom-scenario" id="new_scenario" action="/scenarios" accept-charset="UTF-8" method="post"><input name="utf8" value="✓" type="hidden"><input name="authenticity_token" value="gpHxZfO85mZkubf5u44ddiiebRGr+crdAp1BEn4vu06JIzurgfp/4FoJK2M0I8zFaCJDFAWdlZF6TyopPWAtrA==" type="hidden">


  <div class="form-group">
    <div class="col-lg-10">
      <input class="form-control" name="scenario[name]" id="scenario_name" type="text">
    </div>
    
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <input name="commit" value="Create Scenario" class="btn btn-primary" type="submit">
      <a class="btn btn-default custom-cancel-adding" href="/scenarios">Cancel</a>
    </div>
  </div>

</form>

rails/app/views/scenarios/new.html.erb
<%- model_class = Scenario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

rails/app/views/scenarios/show.html.erb
<%- model_class = Scenario -%>
<div class="page-header">
  <h1>
    Edit <%= @scenario.name %> <%=t '.title', :default => model_class.model_name.human.titleize %>
  </h1>
</div>

<% @groups.each do |group| %>
<div class="group-container">
  <div class="left-aligned">
    <h3>Steps for: <%= group.site_url %></h3>
  </div>
  <div class="right-aligned">
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
    edit_group_path(group), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
    group_path(group),
    :method => :delete,
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
    :class => 'btn btn-default btn-danger' %>
    <a class="btn btn-default custom-show-steps">Show Steps</a>
  </div>
  <ul class="steps-ul">
    <% @steps[group.id].each do |step| %>
    <ul>
      <li><%= link_to step.message, step_path(step) %></li>
      <li><%= step_type(step.step_type) %></li>
      <li style="text-align: right">
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
        edit_step_path(step), :class => 'btn btn-default btn-xs' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
        edit_group_path(group),
        :method => :delete,
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
        :class => 'btn btn-xs btn-danger' %>
      </li>
    </ul>
    <% end %>
    <ul style="text-align: right">
      <li>
      <%= link_to new_step_path, :class => 'btn btn-default btn-xs' do %>
        <i class="fa fa-plus"></i> New Step
      <% end %>
      </li>
    </ul>
  </ul>
</div>
<% end %>
<br />
<%= link_to new_group_path, :class => 'btn btn-default btn-xs' do %>
<i class="fa fa-plus"></i> New Group
<% end %>

<br /> <br />
<%= link_to t('.back', :default => t("helpers.links.back")),
scenarios_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
edit_scenario_path(@scenario), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
scenario_path(@scenario),
:method => 'delete',
:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
:class => 'btn btn-danger' %>

rails/app/views/steps/edit.html.erb
<%- model_class = Step -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

rails/app/views/steps/index.html.erb
<%- model_class = Step -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:message) %></th>
      <th><%= model_class.human_attribute_name(:error_message) %></th>
      <th><%= model_class.human_attribute_name(:options) %></th>
      <th><%= model_class.human_attribute_name(:step_type) %></th>
      <th><%= model_class.human_attribute_name(:group_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= link_to step.id, step_path(step) %></td>
        <td><%= step.message %></td>
        <td><%= step.error_message %></td>
        <td><%= step.options %></td>
        <td><%= step.step_type %></td>
        <td><%= step.group_id %></td>
        <td><%=l step.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_step_path(step), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      step_path(step),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_step_path,
            :class => 'btn btn-primary' %>